import type { AgentRecord, AgentThresholds, AlertRecord, GroupRecord, MetricsSnapshot, SessionInfo, UserRecord } from './models';
export declare function fetchSession(): Promise<SessionInfo>;
export declare function login(username: string, password: string): Promise<SessionInfo>;
export declare function logout(): Promise<void>;
export declare function fetchAgents(): Promise<AgentRecord[]>;
export declare function fetchPendingEnrollments(): Promise<AgentRecord[]>;
export declare function fetchLatestMetrics(): Promise<MetricsSnapshot[]>;
export declare function fetchGroups(): Promise<GroupRecord[]>;
export declare function fetchUsers(): Promise<UserRecord[]>;
export declare function createGroup(name: string): Promise<void>;
export declare function createUser(username: string, password: string, role: UserRecord['role'], groupIds: number[]): Promise<void>;
export declare function fetchAlerts(): Promise<AlertRecord[]>;
export declare function fetchUnacknowledgedAlerts(): Promise<AlertRecord[]>;
export declare function loadDashboardData(): Promise<{
    agents: AgentRecord[];
    pending: AgentRecord[];
    metrics: MetricsSnapshot[];
    groups: GroupRecord[];
    alerts: AlertRecord[];
    users: UserRecord[];
}>;
export declare function approveAgent(agentId: string, groupIds?: number[]): Promise<void>;
export declare function rejectAgent(agentId: string): Promise<void>;
export declare function deleteAgent(agentId: string): Promise<void>;
export declare function setAgentGroups(agentId: string, groupIds: number[]): Promise<void>;
export declare function setAgentInterval(agentId: string, intervalSeconds: number): Promise<void>;
export declare function setAgentProcessLimit(agentId: string, limit: number): Promise<void>;
export declare function setAgentThresholds(agentId: string, thresholds: AgentThresholds): Promise<void>;
export declare function setMaintenance(agentId: string, reason: string, untilMs: number): Promise<void>;
export declare function pauseAgent(agentId: string): Promise<void>;
export declare function resumeAgent(agentId: string): Promise<void>;
export declare function restartAgentCollectors(agentId: string): Promise<void>;
export declare function requestAgentStatus(agentId: string): Promise<void>;
export declare function acknowledgeAlert(alertId: number): Promise<void>;
export declare function deleteAlert(alertId: number): Promise<void>;
