import type { AgentCollectorConfigUpdate, AgentRecord, AgentThresholds, AlertRecord, GroupRecord, LogMatchRecord, MaintenanceWindowRecord, MetricsSnapshot, RunbookRecord, ServerSettings, SessionInfo, SilenceRecord, StatusHistoryRow, UptimeReport, UserRecord, ViewRecord } from './models';
export declare function fetchSession(): Promise<SessionInfo>;
export declare function login(username: string, password: string): Promise<SessionInfo>;
export declare function logout(): Promise<void>;
export declare function fetchAgents(): Promise<AgentRecord[]>;
export declare function fetchPendingEnrollments(): Promise<AgentRecord[]>;
export declare function fetchLatestMetrics(): Promise<MetricsSnapshot[]>;
export declare function fetchGroups(): Promise<GroupRecord[]>;
export declare function fetchUsers(): Promise<UserRecord[]>;
export declare function createGroup(name: string): Promise<void>;
export declare function createUser(username: string, password: string, role: UserRecord['role'], groupIds: number[]): Promise<void>;
export declare function fetchAlerts(includeArchived?: boolean): Promise<AlertRecord[]>;
export declare function fetchUnacknowledgedAlerts(): Promise<AlertRecord[]>;
export declare function loadDashboardData(): Promise<{
    agents: AgentRecord[];
    pending: AgentRecord[];
    metrics: MetricsSnapshot[];
    groups: GroupRecord[];
    alerts: AlertRecord[];
    allAlerts: AlertRecord[];
    users: UserRecord[];
    maintenanceWindows: MaintenanceWindowRecord[];
    silences: SilenceRecord[];
}>;
export declare function approveAgent(agentId: string, groupIds?: number[]): Promise<void>;
export declare function rejectAgent(agentId: string): Promise<void>;
export declare function deleteAgent(agentId: string): Promise<void>;
export declare function setAgentGroups(agentId: string, groupIds: number[]): Promise<void>;
export declare function setAgentInterval(agentId: string, intervalSeconds: number): Promise<void>;
export declare function setAgentProcessLimit(agentId: string, limit: number): Promise<void>;
export declare function setAgentCollectorConfig(agentId: string, update: AgentCollectorConfigUpdate): Promise<void>;
export declare function setAgentThresholds(agentId: string, thresholds: AgentThresholds): Promise<void>;
export declare function setMaintenance(agentId: string, reason: string, untilMs: number): Promise<void>;
export declare function pauseAgent(agentId: string): Promise<void>;
export declare function resumeAgent(agentId: string): Promise<void>;
export declare function restartAgentCollectors(agentId: string): Promise<void>;
export declare function requestAgentStatus(agentId: string): Promise<void>;
export declare function acknowledgeAlert(alertId: number, note?: string): Promise<void>;
export declare function bulkAcknowledgeAlerts(alertIds: number[], note?: string): Promise<void>;
export declare function deleteAlert(alertId: number): Promise<void>;
export declare function archiveAlert(alertId: number): Promise<void>;
export declare function bulkArchiveAlerts(alertIds: number[]): Promise<void>;
export declare function fetchMetricHistory(agentId: string, limit?: number): Promise<MetricsSnapshot[]>;
export declare function fetchUptimeReport(agentId: string, days?: number): Promise<UptimeReport>;
export declare function fetchMaintenanceWindows(): Promise<MaintenanceWindowRecord[]>;
export declare function createMaintenanceWindow(agentId: string, startMs: number, endMs: number, reason: string): Promise<void>;
export declare function deleteMaintenanceWindow(windowId: number): Promise<void>;
export declare function setAgentDescription(agentId: string, description: string): Promise<void>;
export declare function fetchSettings(): Promise<ServerSettings>;
export declare function updateSettings(settings: Partial<ServerSettings>): Promise<void>;
export declare function sendReport(): Promise<{
    sent: boolean;
    report: unknown;
}>;
export declare function disableUser(userId: number): Promise<void>;
export declare function enableUser(userId: number): Promise<void>;
export declare function deleteUser(userId: number): Promise<void>;
export declare function changeUserPassword(userId: number, password: string): Promise<void>;
export declare function fetchSilences(): Promise<SilenceRecord[]>;
export declare function createSilence(agentId: string, indicator: string, reason: string, untilMs: number): Promise<void>;
export declare function deleteSilence(silenceId: number): Promise<void>;
export declare function fetchAgentHistory(agentId: string, limit?: number): Promise<StatusHistoryRow[]>;
export declare function fetchLogMatches(agentId: string, limit?: number): Promise<LogMatchRecord[]>;
export declare function fetchViews(): Promise<ViewRecord[]>;
export declare function createView(name: string, agentIds: string[], isPublic: boolean): Promise<ViewRecord>;
export declare function updateView(viewId: number, name: string, agentIds: string[], isPublic: boolean): Promise<ViewRecord>;
export declare function deleteView(viewId: number): Promise<void>;
export declare function fetchRunbooks(): Promise<RunbookRecord[]>;
export declare function createRunbook(indicator: string, status: string, url: string, notes: string): Promise<RunbookRecord>;
export declare function deleteRunbook(runbookId: number): Promise<void>;
