################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################

if (NOT SODIUM_INCLUDE_DIRS OR NOT SODIUM_LIBRARIES)
  if (NOT MSVC)
    find_package(PkgConfig)
    if (PKG_CONFIG_FOUND)
      pkg_check_modules(PC_SODIUM "libsodium")
      if (PC_SODIUM_FOUND)
        set(pkg_config_names_private "${pkg_config_names_private} libsodium")
      endif()
      if (NOT PC_SODIUM_FOUND)
        pkg_check_modules(PC_SODIUM "sodium")
        if (PC_SODIUM_FOUND)
          set(pkg_config_names_private "${pkg_config_names_private} sodium")
        endif()
      endif (NOT PC_SODIUM_FOUND)
      if (PC_SODIUM_FOUND)
        set(SODIUM_INCLUDE_HINTS ${PC_SODIUM_INCLUDE_DIRS} ${PC_SODIUM_INCLUDE_DIRS}/*)
        set(SODIUM_LIBRARY_HINTS ${PC_SODIUM_LIBRARY_DIRS} ${PC_SODIUM_LIBRARY_DIRS}/*)
      else()
        set(pkg_config_libs_private "${pkg_config_libs_private} -lsodium")
      endif()
    endif()
  endif()

  find_path(
      SODIUM_INCLUDE_DIRS
      NAMES sodium.h
      HINTS ${SODIUM_INCLUDE_HINTS}
  )

  find_library(
      SODIUM_LIBRARIES
      NAMES libsodium sodium
      HINTS ${SODIUM_LIBRARY_HINTS}
  )
endif()

if (SODIUM_INCLUDE_DIRS AND NOT SODIUM_LIBRARIES)
  # The parent Meson build supplies libsodium as an adjacent static target.
  # libzmq only needs the headers while compiling its static archive; the
  # parent target links libsodium into final binaries.
  set(SODIUM_LIBRARIES "libsodium_linked_by_parent_build")
  set(SODIUM_FOUND TRUE)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(sodium DEFAULT_MSG SODIUM_LIBRARIES SODIUM_INCLUDE_DIRS)
mark_as_advanced(SODIUM_FOUND SODIUM_LIBRARIES SODIUM_INCLUDE_DIRS)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
