[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [switch]$SkipWindowsInstall,
    [switch]$InstallWsl,
    [switch]$SkipWsl,
    [string]$LinuxDistro = "Ubuntu",
    [switch]$NoUserBazelrc,
    [switch]$NoVerify
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$UserBazelrc = Join-Path $RepoRoot ".bazelrc.user"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Test-Command {
    param([string]$Name)
    return $null -ne (Get-Command $Name -ErrorAction SilentlyContinue)
}

function Test-IsAdmin {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = [Security.Principal.WindowsPrincipal]::new($identity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Invoke-LoggedCommand {
    param(
        [string]$FilePath,
        [string[]]$Arguments,
        [string]$Description
    )

    $rendered = "$FilePath $($Arguments -join ' ')"
    if ($PSCmdlet.ShouldProcess($Description, $rendered)) {
        & $FilePath @Arguments
        if ($LASTEXITCODE -ne 0) {
            throw "$Description failed with exit code $LASTEXITCODE"
        }
    } else {
        Write-Host "What if: $rendered"
    }
}

function Install-WingetPackage {
    param(
        [string]$Id,
        [string]$Name,
        [string[]]$ExtraArgs = @()
    )

    $args = @(
        "install",
        "--id", $Id,
        "--exact",
        "--accept-package-agreements",
        "--accept-source-agreements"
    ) + $ExtraArgs

    Invoke-LoggedCommand -FilePath "winget" -Arguments $args -Description "Install $Name"
}

function Get-GitBash {
    $candidates = @(
        "C:\Program Files\Git\bin\bash.exe",
        "C:\Program Files\Git\usr\bin\bash.exe",
        "C:\Program Files (x86)\Git\bin\bash.exe",
        "C:\Program Files (x86)\Git\usr\bin\bash.exe"
    )

    foreach ($candidate in $candidates) {
        if (Test-Path $candidate) {
            return (Resolve-Path $candidate).Path
        }
    }

    $fromPath = Get-Command "bash.exe" -ErrorAction SilentlyContinue
    if ($null -ne $fromPath -and $fromPath.Source -like "*\Git\*") {
        return $fromPath.Source
    }

    return $null
}

function Convert-ToShortPath {
    param([string]$Path)

    try {
        $item = Get-Item -LiteralPath $Path -ErrorAction Stop
        $fso = New-Object -ComObject Scripting.FileSystemObject
        if ($item.PSIsContainer) {
            return $fso.GetFolder($item.FullName).ShortPath.Replace("\", "/")
        }

        return $fso.GetFile($item.FullName).ShortPath.Replace("\", "/")
    } catch {
        return $Path.Replace("\", "/")
    }
}

function Get-VsWhere {
    $candidate = Join-Path ${env:ProgramFiles(x86)} "Microsoft Visual Studio\Installer\vswhere.exe"
    if (Test-Path $candidate) {
        return $candidate
    }

    return $null
}

function Test-VisualCppTools {
    $vswhere = Get-VsWhere
    if ($null -eq $vswhere) {
        return $false
    }

    $install = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
    return -not [string]::IsNullOrWhiteSpace($install)
}

function Write-BazelUserRc {
    param([string]$GitBashPath)

    $gitBin = Split-Path $GitBashPath -Parent
    $gitRoot = Split-Path $gitBin -Parent
    $gitUsrBin = Join-Path $gitRoot "usr\bin"

    $bazelBash = Convert-ToShortPath $GitBashPath
    $pathParts = @(
        (Convert-ToShortPath $gitBin),
        (Convert-ToShortPath $gitUsrBin),
        "C:/WINDOWS/system32",
        "C:/WINDOWS",
        "C:/WINDOWS/System32/WindowsPowerShell/v1.0"
    )

    $content = @"
# Generated by scripts/setup-build-env.ps1.
# Keeps Bazel Windows actions on Git Bash instead of C:\Windows\System32\bash.exe,
# which is the WSL launcher and fails when no distro is initialized.
build:windows --action_env=BAZEL_SH=$bazelBash
build:windows --action_env=PATH=$($pathParts -join ";")
build:windows --host_action_env=BAZEL_SH=$bazelBash
build:windows --host_action_env=PATH=$($pathParts -join ";")
"@

    if ($PSCmdlet.ShouldProcess($UserBazelrc, "Write Bazel user configuration")) {
        Set-Content -Path $UserBazelrc -Value $content -Encoding ASCII
    } else {
        Write-Host "What if: write $UserBazelrc"
        Write-Host $content
    }
}

function Set-UserBazelEnvironment {
    param([string]$GitBashPath)

    $bazelBash = Convert-ToShortPath $GitBashPath
    if ($PSCmdlet.ShouldProcess("User environment", "Set BAZEL_SH=$bazelBash")) {
        [Environment]::SetEnvironmentVariable("BAZEL_SH", $bazelBash, "User")
        $env:BAZEL_SH = $bazelBash
    } else {
        Write-Host "What if: set user BAZEL_SH=$bazelBash"
    }
}

function Stop-BazelServer {
    $bazelCommand = $null
    if (Test-Command "bazelisk") {
        $bazelCommand = "bazelisk"
    } elseif (Test-Command "bazel") {
        $bazelCommand = "bazel"
    }

    if ($null -eq $bazelCommand) {
        Write-Host "Bazelisk or Bazel is not on PATH yet; skipping Bazel server shutdown."
        return
    }

    Invoke-LoggedCommand -FilePath $bazelCommand -Arguments @("shutdown") -Description "Restart Bazel server so .bazelrc changes apply"
}

function Install-WindowsDependencies {
    if (-not (Test-Command "winget")) {
        throw "winget is required. Install App Installer from Microsoft Store, then rerun this script."
    }

    if (-not (Test-Command "git")) {
        Install-WingetPackage -Id "Git.Git" -Name "Git for Windows"
    } else {
        Write-Host "Git is already available."
    }

    if (-not ((Test-Command "bazelisk") -or (Test-Command "bazel"))) {
        Install-WingetPackage -Id "Bazel.Bazelisk" -Name "Bazelisk"
    } else {
        Write-Host "Bazelisk or Bazel is already available."
    }

    if (-not (Test-VisualCppTools)) {
        Install-WingetPackage `
            -Id "Microsoft.VisualStudio.2022.BuildTools" `
            -Name "Visual Studio 2022 Build Tools" `
            -ExtraArgs @(
                "--override",
                "--wait --quiet --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --add Microsoft.VisualStudio.Component.Windows11SDK.26100"
            )
    } else {
        Write-Host "Visual C++ Build Tools are already installed."
    }
}

function Install-WslDependencies {
    if ($SkipWsl) {
        Write-Host "Skipping WSL setup."
        return
    }

    if (-not $InstallWsl) {
        Write-Host "Skipping WSL setup. Pass -InstallWsl to install a Linux build environment."
        return
    }

    if (-not (Test-IsAdmin)) {
        throw "WSL installation requires an elevated PowerShell session."
    }

    $distros = @()
    if (Test-Command "wsl.exe") {
        $distros = @(wsl.exe --list --quiet 2>$null | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
    }

    if ($distros.Count -eq 0) {
        Invoke-LoggedCommand -FilePath "wsl.exe" -Arguments @("--install", "-d", $LinuxDistro) -Description "Install WSL distro $LinuxDistro"
        Write-Warning "If WSL requested a reboot or first-user setup, complete that first and rerun this script."
        return
    }

    Write-Host "WSL distro detected: $($distros -join ', ')"
    $packages = "build-essential clang lld git pkg-config autoconf automake libtool make cmake unzip zip curl ca-certificates"
    Invoke-LoggedCommand `
        -FilePath "wsl.exe" `
        -Arguments @("-d", $LinuxDistro, "--", "bash", "-lc", "sudo apt-get update && sudo apt-get install -y $packages") `
        -Description "Install Linux build packages in WSL"

    $bazeliskInstall = "tmp=`$(mktemp) && curl -fsSL https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -o `$tmp && sudo install -m 0755 `$tmp /usr/local/bin/bazelisk && sudo ln -sf /usr/local/bin/bazelisk /usr/local/bin/bazel && rm -f `$tmp"
    Invoke-LoggedCommand `
        -FilePath "wsl.exe" `
        -Arguments @("-d", $LinuxDistro, "--", "bash", "-lc", $bazeliskInstall) `
        -Description "Install Bazelisk in WSL"
}

function Test-Environment {
    Write-Step "Environment verification"

    $gitBash = Get-GitBash
    if ([string]::IsNullOrWhiteSpace($gitBash)) {
        throw "Git Bash was not found. Install Git for Windows and rerun this script."
    }
    Write-Host "Git Bash: $gitBash"
    & $gitBash -lc "echo git-bash-ok"

    if (Test-Command "bazelisk") {
        bazelisk version
    } elseif (Test-Command "bazel") {
        bazel version
    } else {
        throw "Bazelisk or Bazel was not found on PATH."
    }

    if (-not (Test-VisualCppTools)) {
        throw "Visual C++ Build Tools were not detected by vswhere."
    }
    Write-Host "Visual C++ Build Tools: detected"

    if (-not (Test-Path $UserBazelrc)) {
        throw ".bazelrc.user was not found at $UserBazelrc"
    }
    Write-Host "Bazel user config: $UserBazelrc"
}

if ($InstallWsl -and $SkipWsl) {
    throw "Use either -InstallWsl or -SkipWsl, not both."
}

Write-Step "TheWatcher build environment setup"
Write-Host "Repository: $RepoRoot"

if (-not $SkipWindowsInstall) {
    Write-Step "Windows build dependencies"
    Install-WindowsDependencies
} else {
    Write-Host "Skipping Windows dependency installation."
}

Write-Step "Bazel Windows shell configuration"
$gitBashPath = Get-GitBash
if ([string]::IsNullOrWhiteSpace($gitBashPath)) {
    if ($SkipWindowsInstall) {
        throw "Git Bash was not found. Rerun without -SkipWindowsInstall or install Git for Windows manually."
    }

    Write-Warning "Git Bash was not found in this PowerShell session. Open a new PowerShell window after installation and rerun this script."
} elseif (-not $NoUserBazelrc) {
    Write-BazelUserRc -GitBashPath $gitBashPath
    Set-UserBazelEnvironment -GitBashPath $gitBashPath
    Stop-BazelServer
} else {
    Write-Host "Skipping .bazelrc.user generation."
}

Write-Step "Optional WSL/Linux build dependencies"
Install-WslDependencies

if (-not $NoVerify) {
    Test-Environment
}

Write-Host ""
Write-Host "Setup complete. Open a new PowerShell window if this script installed new tools." -ForegroundColor Green
